[package]
name = "sec1_4"
version = "0.1.0"
authors = ["Liing Pang Ryan <ryanfx1998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
