[package]
authors = ["Liing Pang Ryan <ryanfx1998@gmail.com>"]
edition = "2018"
name = "Ex_3"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
rayon_logs = "*"
